// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from './lib/CartContext';
import { AuthProvider } from "@/app/auth/utils/AuthContext";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// }); 

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Wrap the whole layout with both AuthProvider and CartProvider */}
        <AuthProvider>
          <CartProvider>
            <Navbar />
            {/* Main content of the page */}
            {children}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
